stages:
  - depoly

depoly-qa:
  stage: depoly
  script:
    - devops dp --lintCheck=false --delOutputDir=false
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /^qatest/'
  tags:
    - qa-node:12.18

depoly-pre:
  stage: depoly
  script:
    - devops dp --lintCheck=false --delOutputDir=false
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /^pre-release/'
  tags:
    - pre-node:12.18

depoly-prod:
  stage: depoly
  script:
    - devops dp --lintCheck=false --delOutputDir=false
  rules:
    - if: '$CI_COMMIT_TAG'
  tags:
    - prod-node:12.18
